name: Main Branch Push
run-name: ${{ github.actor }} pushed new changes into main
on:
  push:
    branches: ["main"]

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-test.yml
    with:
      # node-version: ${{ vars.NODE_VERSION }}
      node-version: 20

  deploy-develop:
    needs: unit-tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node env
        uses: ./.github/workflows/node-setup.yml
        with:
          # node-version: ${{ vars.NODE_VERSION }}
          node-version: 20

      - name: CDK deploy
        id: cdk-deploy
        run: |
          echo "cdk deploy"

  acceptance-tests:
    needs: deploy-develop
    name: Acceptance Tests
    uses: ./.github/workflows/acceptance-test.yml
    with:
      # node-version: ${{ vars.NODE_VERSION }}
      node-version: 20
    secrets: inherit

  notification-success:
    name: Slack success notification
    needs: [unit-tests, deploy-develop, acceptance-tests]
    runs-on: ubuntu-latest
    if: ${{ needs.unit-tests.result == 'success' && needs.deploy-develop.result == 'success' && needs.acceptance-tests.result == 'success' }}
    steps:
      - name: Slack success notification
        id: success-notif
        run: |
          echo "Notify successful run"

  notification-failure:
    name: Slack failure notification
    needs: [unit-tests, deploy-develop, acceptance-tests]
    runs-on: ubuntu-latest
    if: ${{ needs.unit-tests.result == 'failure' || needs.deploy-develop.result == 'failure' || needs.acceptance-tests.result == 'failure' }}
    steps:
      - name: Slack failure notification
        id: failure-notif
        run: |
          echo "Notify failure run"

  show-job-status:
    name: Show jobs exit status
    needs: [unit-tests, deploy-develop, acceptance-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Show jobs exit status
        id: show-job-status
        run: |
          echo needs.unit-tests.result = ${{ needs.unit-tests.result }}
          echo needs.deploy-develop.result = ${{ needs.deploy-develop.result }}
          echo needs.acceptance-tests.result = ${{ needs.acceptance-tests.result }}
